language: node_js
node_js:
  - 12
cache: yarn
before_deploy:
  - yarn install --frozen-lockfile --ignore-engines
deploy:
  email: "jeniksilhan@gmail.com"
  provider: script
  script:
    - yarn install --frozen-lockfile --ignore-engines && yarn release
  on:
    branch: master
