language: node_js
node_js:
  - 12
cache: yarn
before_deploy:
  - npm install -g @beemo/cli
  - yarn install --frozen-lockfile --ignore-engines
deploy:
  skip_cleanup: true
  email: "jeniksilhan@gmail.com"
  provider: script
  script: deploy.sh
  on:
    branch: master
