name: Primary code validation

on:
  push:
    branches-ignore:
      - master
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 15]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --ignore-engines --frozen-lockfile
      - run: yarn test
